services:
  # --- O Porteiro (Traefik) ---
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=false" # Desliga painel inseguro
      - "--providers.docker=true" # Habilita leitura do Docker
      - "--providers.docker.exposedbydefault=false" # Só expõe quem pedir explicitamente
      - "--entrypoints.web.address=:80" # Porta HTTP
      - "--entrypoints.websecure.address=:443" # Porta HTTPS
      # Configuração do Let's Encrypt (Certificado Automático)
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=seuemail@exemplo.com" # <--- TROQUE PELO SEU EMAIL
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # ADICIONE ESTA LINHA ABAIXO PARA GARANTIR:
      - "--providers.docker.apiVersion=1.44"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt" # Onde salva os certificados
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Permissão para ler o Docker
    networks:
      - app_network

  # --- O Banco de Dados (Postgres) ---
  db:
    image: postgres:15
    container_name: postgres_prod
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pg_data_prod:/var/lib/postgresql/data # Pasta diferente do local!
    networks:
      - app_network
    # Note: SEM "ports". Ninguém acessa o banco de fora, só o Django.

  # --- O Backend (Django) ---
  api:
    build: .
    container_name: django_api
    restart: always
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media_prod:/app/media # Onde salvamos as imagens de upload
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network
    labels:
      - "traefik.enable=true"
      # Regra: Se o domínio for api.seudominio.com, mande pra cá
      - "traefik.http.routers.api.rule=Host(`api.seudominio.com.br`)" # <--- TROQUE PELO SEU DOMÍNIO
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      # Redirecionar HTTP para HTTPS automaticamente é feito globalmente ou aqui, 
      # mas com Cloudflare 'Full', o tráfego já chega criptografado muitas vezes.

networks:
  app_network:
    driver: bridge